---
title: "Manipulando tabela estraída da Propesq"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

<style>
div.hidecode + pre {display: none}
</style>



### Setup

**Bibliotecas**
```{r}
library(tidyverse)
library(patchwork)
```

**Dataset**
```{r}
propesq <- "../data/propesq.rds" %>% read_rds()
```

**Tema para gráfico**
```{r}
tema <- function(titulo="", nota="", facet) {
  
  t <- list(
            theme(axis.text.x = element_text(angle=90)),
            facet_wrap(facets=facet, scales="free_y", ncol = 1),
            labs(title = titulo,
                 caption = nota) 
        )
  
  return(t)

}
```

### Municípios

<details>
    <summary>
    Ver Código
    </summary>

```{r}

plot.kg <- propesq %>% 
  group_by(municipio, periodo) %>%
  summarise(kg = sum(kg)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x = periodo, y = kg/1000, color = factor(municipio)), show.legend = F) + 
  tema(titulo = "Kg", nota = "Em milhares", facet="municipio")

plot.vlr <- propesq %>% 
  group_by(municipio, periodo) %>%
  summarise(valor_estimado = sum(valor_estimado)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x = periodo, y = valor_estimado/1000, color = factor(municipio)), show.legend = F) +
  tema(titulo = "R$", nota = "Em milhares", facet="municipio")

plot.dscg <- propesq %>% 
  group_by(municipio, periodo) %>%
  summarise(qtd_descargas = sum(qtd_descargas)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x=periodo, y=qtd_descargas, color=factor(municipio)), show.legend = F) +
  tema(titulo = "Descargas", facet="municipio")

plot.un_prd <- propesq %>% 
  group_by(municipio, periodo) %>%
  summarise(qtd_unidades_produtivas = sum(qtd_unidades_produtivas)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x=periodo, y=qtd_unidades_produtivas, color=factor(municipio)), show.legend = F) +
  tema(titulo = "Un. Produtivas", facet="municipio") 
```
</details>

```{r echo=FALSE, fig.align='center', fig.height=20, fig.width=15}
plot.kg | plot.vlr | plot.un_prd | plot.dscg
```

### Nível taxonômico

<details>
    <summary>
    Ver Código
    </summary>
    
```{r}
plot.preco <- propesq %>%
  na.omit(nivel_taxonomico) %>%
  filter(nivel_taxonomico != "Equinodermo") %>%
  group_by(nivel_taxonomico, periodo) %>%
  summarise(preco = sum(valor_estimado) / sum(kg)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x=periodo, y=preco, color=factor(nivel_taxonomico)), show.legend = F) +
  tema(titulo = "Preço", facet="nivel_taxonomico") 

plot.kg <- propesq %>%
  na.omit(nivel_taxonomico) %>%
  filter(nivel_taxonomico != "Equinodermo") %>%
  group_by(nivel_taxonomico, periodo) %>%
  summarise(kg = sum(kg)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x=periodo, y=kg/1000, color=factor(nivel_taxonomico)), show.legend = F) +
  tema(titulo = "Kg", facet="nivel_taxonomico") 

plot.produtividade_barco <-  propesq %>%
  na.omit(nivel_taxonomico) %>%
  filter(nivel_taxonomico != "Equinodermo") %>%
  group_by(nivel_taxonomico, periodo) %>%
  summarise(produtividade = sum(kg) / sum(qtd_unidades_produtivas)) %>%
  ungroup() %>%
  ggplot() + 
  geom_line(aes(x=periodo, y=produtividade, color=factor(nivel_taxonomico)), show.legend = F) +
  tema(titulo = "Produtividade", facet="nivel_taxonomico") 
```
</details>

```{r echo=FALSE, fig.align='center', fig.height=20, fig.width=15}
plot.preco | plot.kg | plot.produtividade_barco
```

